// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQS0r-EQ_gWqfgyX0u7ldlsGSkOT9DEQ',
    appId: '1:157353142317:web:8b274f849039245aadb0a4',
    messagingSenderId: '157353142317',
    projectId: 'task365-d754b',
    authDomain: 'task365-d754b.firebaseapp.com',
    storageBucket: 'task365-d754b.firebasestorage.app',
    measurementId: 'G-EQP765TSXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kh2xz1jLucCjxZ3q0Wo9OgKicLuOOig',
    appId: '1:157353142317:android:b56e89685a9725c4adb0a4',
    messagingSenderId: '157353142317',
    projectId: 'task365-d754b',
    storageBucket: 'task365-d754b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSYFeS0bbHHKzCUE4z-ZAbaVSR5smL0NI',
    appId: '1:157353142317:ios:b74a8a1e159c59e5adb0a4',
    messagingSenderId: '157353142317',
    projectId: 'task365-d754b',
    storageBucket: 'task365-d754b.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSYFeS0bbHHKzCUE4z-ZAbaVSR5smL0NI',
    appId: '1:157353142317:ios:b74a8a1e159c59e5adb0a4',
    messagingSenderId: '157353142317',
    projectId: 'task365-d754b',
    storageBucket: 'task365-d754b.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGQS0r-EQ_gWqfgyX0u7ldlsGSkOT9DEQ',
    appId: '1:157353142317:web:70ed99c669a29e40adb0a4',
    messagingSenderId: '157353142317',
    projectId: 'task365-d754b',
    authDomain: 'task365-d754b.firebaseapp.com',
    storageBucket: 'task365-d754b.firebasestorage.app',
    measurementId: 'G-S6LLC605SK',
  );
}
